"""Create functional P0 schema

Revision ID: 7b1ac80518a7
Revises: 
Create Date: 2026-07-24 01:50:06.651834
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7b1ac80518a7'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymous_devices',
    sa.Column('installation_id_hash', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('locale', sa.String(length=20), nullable=True),
    sa.Column('region_code', sa.String(length=40), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anonymous_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anonymous_devices_installation_id_hash'), ['installation_id_hash'], unique=True)

    op.create_table('audit_logs',
    sa.Column('incident_id', sa.String(length=36), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('request_id', sa.String(length=80), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_incident_id'), ['incident_id'], unique=False)

    op.create_table('background_jobs',
    sa.Column('job_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_status'), ['status'], unique=False)

    op.create_table('idempotency_records',
    sa.Column('actor_key', sa.String(length=100), nullable=False),
    sa.Column('route', sa.String(length=200), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_key', 'route', 'idempotency_key')
    )
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_records_expires_at'), ['expires_at'], unique=False)

    op.create_table('incidents',
    sa.Column('alias', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('center_latitude', sa.Float(), nullable=True),
    sa.Column('center_longitude', sa.Float(), nullable=True),
    sa.Column('map_coordinate_system', sa.String(length=12), nullable=False),
    sa.Column('map_default_zoom', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('feature_flags', sa.JSON(), nullable=False),
    sa.Column('event_sequence', sa.Integer(), nullable=False),
    sa.Column('data_revision', sa.Integer(), nullable=False),
    sa.Column('map_revision', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_status'), ['status'], unique=False)
        batch_op.create_index('uq_incidents_single_active', ['status'], unique=True, sqlite_where=sa.text("status = 'active'"))

    op.create_table('local_accounts',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('local_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_local_accounts_username'), ['username'], unique=True)

    op.create_table('refresh_sessions',
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('issued_token_version', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_sessions_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_sessions_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_sessions_subject_type'), ['subject_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_sessions_token_hash'), ['token_hash'], unique=True)

    op.create_table('ai_analyses',
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('context_package', sa.JSON(), nullable=True),
    sa.Column('context_sha256', sa.String(length=64), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_provider', sa.String(length=80), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.String(length=300), nullable=True),
    sa.Column('created_by_type', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('input_version', sa.Integer(), nullable=False),
    sa.Column('data_as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('stale_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stale_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_analyses_analysis_type'), ['analysis_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analyses_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analyses_status'), ['status'], unique=False)

    op.create_table('blind_spots',
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('claim_key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('location_text', sa.String(length=300), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('coordinate_system', sa.String(length=12), nullable=True),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('scope_data', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('route_impact_count', sa.Integer(), nullable=False),
    sa.Column('min_valid_answers', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution_value', sa.String(length=100), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blind_spots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blind_spots_claim_key'), ['claim_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_blind_spots_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blind_spots_status'), ['status'], unique=False)

    op.create_table('conflict_cases',
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('fact_key', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('topic', sa.String(length=60), nullable=False),
    sa.Column('location_text', sa.String(length=300), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('coordinate_system', sa.String(length=12), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.JSON(), nullable=True),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    with op.batch_alter_table('conflict_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conflict_cases_fact_key'), ['fact_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_conflict_cases_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conflict_cases_status'), ['status'], unique=False)

    op.create_table('incident_fact_records',
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('fact_key', sa.String(length=120), nullable=False),
    sa.Column('topic', sa.String(length=60), nullable=False),
    sa.Column('location_text', sa.String(length=300), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('coordinate_system', sa.String(length=12), nullable=True),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('current_revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'fact_key')
    )
    with op.batch_alter_table('incident_fact_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_fact_records_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_fact_records_status'), ['status'], unique=False)

    op.create_table('incident_memberships',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['local_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'incident_id')
    )
    op.create_table('information_fragments',
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_ref_id', sa.String(length=36), nullable=True),
    sa.Column('source_cluster_id', sa.String(length=36), nullable=True),
    sa.Column('topic', sa.String(length=60), nullable=False),
    sa.Column('claim_key', sa.String(length=100), nullable=True),
    sa.Column('claim_value', sa.String(length=100), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location_text', sa.String(length=300), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('coordinate_system', sa.String(length=12), nullable=True),
    sa.Column('shape', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('information_fragments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_information_fragments_claim_key'), ['claim_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_information_fragments_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_information_fragments_source_ref_id'), ['source_ref_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_information_fragments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_information_fragments_topic'), ['topic'], unique=False)

    op.create_table('map_features',
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('source_ref', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('latitude_wgs84', sa.Float(), nullable=True),
    sa.Column('longitude_wgs84', sa.Float(), nullable=True),
    sa.Column('latitude_gcj02', sa.Float(), nullable=True),
    sa.Column('longitude_gcj02', sa.Float(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('public_data', sa.JSON(), nullable=False),
    sa.Column('private_data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'kind', 'source_ref')
    )
    with op.batch_alter_table('map_features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_map_features_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_map_features_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_map_features_latitude_wgs84'), ['latitude_wgs84'], unique=False)
        batch_op.create_index(batch_op.f('ix_map_features_longitude_wgs84'), ['longitude_wgs84'], unique=False)

    op.create_table('outbox_events',
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('resource_revision', sa.Integer(), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=True),
    sa.Column('owner_device_id', sa.String(length=36), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('request_id', sa.String(length=80), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('publish_attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'sequence')
    )
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_published_at'), ['published_at'], unique=False)

    op.create_table('reports',
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('reporter_device_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('content_original', sa.Text(), nullable=False),
    sa.Column('content_display', sa.Text(), nullable=False),
    sa.Column('location_text', sa.String(length=300), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_wgs84_latitude', sa.Float(), nullable=True),
    sa.Column('location_wgs84_longitude', sa.Float(), nullable=True),
    sa.Column('location_gcj02_latitude', sa.Float(), nullable=True),
    sa.Column('location_gcj02_longitude', sa.Float(), nullable=True),
    sa.Column('location_accuracy_m', sa.Float(), nullable=True),
    sa.Column('location_source', sa.String(length=20), nullable=False),
    sa.Column('coordinate_system', sa.String(length=12), nullable=True),
    sa.Column('location_provider', sa.String(length=30), nullable=True),
    sa.Column('location_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('coordinate_algorithm_version', sa.String(length=40), nullable=True),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.String(length=12), nullable=False),
    sa.Column('priority_source', sa.String(length=30), nullable=False),
    sa.Column('manual_priority', sa.String(length=12), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_directed_answer', sa.Boolean(), nullable=False),
    sa.Column('directed_answer_id', sa.String(length=36), nullable=True),
    sa.Column('ai_refinement_id', sa.String(length=36), nullable=True),
    sa.Column('attachment_count', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['reporter_device_id'], ['anonymous_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index('ix_reports_incident_priority_updated', ['incident_id', 'priority', 'updated_at'], unique=False)
        batch_op.create_index('ix_reports_incident_updated', ['incident_id', 'updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_is_urgent'), ['is_urgent'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_reporter_device_id'), ['reporter_device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_status'), ['status'], unique=False)

    op.create_table('ai_job_steps',
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_job_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_job_steps_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('conflict_decisions',
    sa.Column('conflict_id', sa.String(length=36), nullable=False),
    sa.Column('conflict_revision', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_decisions', sa.JSON(), nullable=False),
    sa.Column('conclusion', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analyses.id'], ),
    sa.ForeignKeyConstraint(['conflict_id'], ['conflict_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conflict_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conflict_decisions_conflict_id'), ['conflict_id'], unique=False)

    op.create_table('conflict_evidence',
    sa.Column('conflict_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('source_revision', sa.Integer(), nullable=False),
    sa.Column('source_cluster_id', sa.String(length=36), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('snapshot_sha256', sa.String(length=64), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['conflict_id'], ['conflict_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conflict_id', 'kind', 'source_id', 'source_revision')
    )
    with op.batch_alter_table('conflict_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conflict_evidence_conflict_id'), ['conflict_id'], unique=False)

    op.create_table('directed_questions',
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('blind_spot_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('location_text', sa.String(length=300), nullable=False),
    sa.Column('target_geometry', sa.JSON(), nullable=True),
    sa.Column('route_impact_count', sa.Integer(), nullable=False),
    sa.Column('answer_type', sa.String(length=30), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blind_spot_id'], ['blind_spots.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('directed_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_directed_questions_blind_spot_id'), ['blind_spot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_directed_questions_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_directed_questions_status'), ['status'], unique=False)

    op.create_table('incident_fact_versions',
    sa.Column('fact_record_id', sa.String(length=36), nullable=False),
    sa.Column('previous_version_id', sa.String(length=36), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_conflict_id', sa.String(length=36), nullable=True),
    sa.Column('source_analysis_id', sa.String(length=36), nullable=True),
    sa.Column('context_snapshot', sa.JSON(), nullable=True),
    sa.Column('accepted_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('decision_snapshot', sa.JSON(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['fact_record_id'], ['incident_fact_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fact_record_id', 'revision')
    )
    op.create_table('report_attachments',
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('uploader_device_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('declared_mime_type', sa.String(length=80), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('expected_sha256', sa.String(length=64), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('perceptual_hash', sa.String(length=64), nullable=True),
    sa.Column('duplicate_of_attachment_id', sa.String(length=36), nullable=True),
    sa.Column('source_cluster_id', sa.String(length=36), nullable=True),
    sa.Column('original_path', sa.String(length=500), nullable=True),
    sa.Column('sanitized_path', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exif_data', sa.JSON(), nullable=True),
    sa.Column('metadata_status', sa.String(length=20), nullable=False),
    sa.Column('malware_scan_status', sa.String(length=20), nullable=False),
    sa.Column('ocr_status', sa.String(length=20), nullable=False),
    sa.Column('vision_status', sa.String(length=20), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('vision_summary', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=300), nullable=True),
    sa.Column('upload_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['uploader_device_id'], ['anonymous_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_attachments_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_attachments_perceptual_hash'), ['perceptual_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_attachments_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_attachments_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_attachments_source_cluster_id'), ['source_cluster_id'], unique=False)

    op.create_table('report_revisions',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('changed_by_type', sa.String(length=20), nullable=False),
    sa.Column('changed_by_id', sa.String(length=36), nullable=True),
    sa.Column('change_reason', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'revision')
    )
    op.create_table('directed_answers',
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('option_id', sa.String(length=80), nullable=False),
    sa.Column('semantic_value', sa.String(length=100), nullable=False),
    sa.Column('answer_text', sa.String(length=300), nullable=False),
    sa.Column('observed_latitude', sa.Float(), nullable=True),
    sa.Column('observed_longitude', sa.Float(), nullable=True),
    sa.Column('observed_coordinate_system', sa.String(length=12), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['anonymous_devices.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['directed_questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'device_id')
    )
    op.create_table('directed_answer_revisions',
    sa.Column('answer_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['directed_answers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_id', 'revision')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('directed_answer_revisions')
    op.drop_table('directed_answers')
    op.drop_table('report_revisions')
    with op.batch_alter_table('report_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_attachments_source_cluster_id'))
        batch_op.drop_index(batch_op.f('ix_report_attachments_sha256'))
        batch_op.drop_index(batch_op.f('ix_report_attachments_report_id'))
        batch_op.drop_index(batch_op.f('ix_report_attachments_perceptual_hash'))
        batch_op.drop_index(batch_op.f('ix_report_attachments_incident_id'))

    op.drop_table('report_attachments')
    op.drop_table('incident_fact_versions')
    with op.batch_alter_table('directed_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_directed_questions_status'))
        batch_op.drop_index(batch_op.f('ix_directed_questions_incident_id'))
        batch_op.drop_index(batch_op.f('ix_directed_questions_blind_spot_id'))

    op.drop_table('directed_questions')
    with op.batch_alter_table('conflict_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conflict_evidence_conflict_id'))

    op.drop_table('conflict_evidence')
    with op.batch_alter_table('conflict_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conflict_decisions_conflict_id'))

    op.drop_table('conflict_decisions')
    with op.batch_alter_table('ai_job_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_job_steps_analysis_id'))

    op.drop_table('ai_job_steps')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_status'))
        batch_op.drop_index(batch_op.f('ix_reports_reporter_device_id'))
        batch_op.drop_index(batch_op.f('ix_reports_priority'))
        batch_op.drop_index(batch_op.f('ix_reports_is_urgent'))
        batch_op.drop_index('ix_reports_incident_updated')
        batch_op.drop_index('ix_reports_incident_priority_updated')
        batch_op.drop_index(batch_op.f('ix_reports_incident_id'))
        batch_op.drop_index(batch_op.f('ix_reports_category'))

    op.drop_table('reports')
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_events_published_at'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_incident_id'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_event_type'))

    op.drop_table('outbox_events')
    with op.batch_alter_table('map_features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_map_features_longitude_wgs84'))
        batch_op.drop_index(batch_op.f('ix_map_features_latitude_wgs84'))
        batch_op.drop_index(batch_op.f('ix_map_features_kind'))
        batch_op.drop_index(batch_op.f('ix_map_features_incident_id'))

    op.drop_table('map_features')
    with op.batch_alter_table('information_fragments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_information_fragments_topic'))
        batch_op.drop_index(batch_op.f('ix_information_fragments_status'))
        batch_op.drop_index(batch_op.f('ix_information_fragments_source_ref_id'))
        batch_op.drop_index(batch_op.f('ix_information_fragments_incident_id'))
        batch_op.drop_index(batch_op.f('ix_information_fragments_claim_key'))

    op.drop_table('information_fragments')
    op.drop_table('incident_memberships')
    with op.batch_alter_table('incident_fact_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_fact_records_status'))
        batch_op.drop_index(batch_op.f('ix_incident_fact_records_incident_id'))

    op.drop_table('incident_fact_records')
    with op.batch_alter_table('conflict_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conflict_cases_status'))
        batch_op.drop_index(batch_op.f('ix_conflict_cases_incident_id'))
        batch_op.drop_index(batch_op.f('ix_conflict_cases_fact_key'))

    op.drop_table('conflict_cases')
    with op.batch_alter_table('blind_spots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blind_spots_status'))
        batch_op.drop_index(batch_op.f('ix_blind_spots_incident_id'))
        batch_op.drop_index(batch_op.f('ix_blind_spots_claim_key'))

    op.drop_table('blind_spots')
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_analyses_status'))
        batch_op.drop_index(batch_op.f('ix_ai_analyses_incident_id'))
        batch_op.drop_index(batch_op.f('ix_ai_analyses_analysis_type'))

    op.drop_table('ai_analyses')
    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_subject_type'))
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_subject_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_family_id'))

    op.drop_table('refresh_sessions')
    with op.batch_alter_table('local_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_local_accounts_username'))

    op.drop_table('local_accounts')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index('uq_incidents_single_active', sqlite_where=sa.text("status = 'active'"))
        batch_op.drop_index(batch_op.f('ix_incidents_status'))

    op.drop_table('incidents')
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_records_expires_at'))

    op.drop_table('idempotency_records')
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_job_type'))

    op.drop_table('background_jobs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_incident_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('anonymous_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anonymous_devices_installation_id_hash'))

    op.drop_table('anonymous_devices')
    # ### end Alembic commands ###
